name: Verify Platform State

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: verification
        run: echo "Platform state verified successfuly!"
        
  merge-me:
    name: Merge me!
    needs:
      - verify
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
